//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Bot.Sample.AspNetCore.AnnotatedSandwichBot.Resource {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Microsoft_Bot_Sample_JsonSandwichBot_SandwichOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Microsoft_Bot_Sample_JsonSandwichBot_SandwichOrder() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Bot.Sample.AspNetCore.AnnotatedSandwichBot.Resource.Microsoft.Bot.Sampl" +
                            "e.JsonSandwichBot.SandwichOrder", typeof(Microsoft_Bot_Sample_JsonSandwichBot_SandwichOrder).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to order your {Length} {Sandwich} on {Ingredients.Bread} {&amp;Ingredients.Bread} with {[{Ingredients.Cheese} {Ingredients.Toppings} {Ingredients.Sauces}]} to be sent to {DeliveryAddress} {?at {DeliveryTime:t}}? 的本地化字符串。
        /// </summary>
        public static string confirmation12_promptDefinition_LIST {
            get {
                return ResourceManager.GetString("confirmation12_promptDefinition;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delivery Address 的本地化字符串。
        /// </summary>
        public static string DeliveryAddress_description_VALUE {
            get {
                return ResourceManager.GetString("DeliveryAddress_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 deliverys?;address?;deliverys? address? 的本地化字符串。
        /// </summary>
        public static string DeliveryAddress_terms_LIST {
            get {
                return ResourceManager.GetString("DeliveryAddress_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delivery Time 的本地化字符串。
        /// </summary>
        public static string DeliveryTime_description_VALUE {
            get {
                return ResourceManager.GetString("DeliveryTime_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What time do you want your sandwich delivered? {||} 的本地化字符串。
        /// </summary>
        public static string DeliveryTime_promptDefinition_LIST {
            get {
                return ResourceManager.GetString("DeliveryTime_promptDefinition;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 deliverys?;times?;deliverys? times? 的本地化字符串。
        /// </summary>
        public static string DeliveryTime_terms_LIST {
            get {
                return ResourceManager.GetString("DeliveryTime_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What kind of {&amp;} would you like on your sandwich? {||} 的本地化字符串。
        /// </summary>
        public static string EnumSelectOne_Sandwich_Length_Ingredients_Bread_Ingredients_Cheese_Ingredients_Toppings_Ingredients_Sauces_Specials_DeliveryAddress_DeliveryTime_Rating_TEMPLATE {
            get {
                return ResourceManager.GetString("EnumSelectOne;Sandwich;Length;Ingredients.Bread;Ingredients.Cheese;Ingredients.To" +
                        "ppings;Ingredients.Sauces;Specials;DeliveryAddress;DeliveryTime;Rating;TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bread 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_description_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Bread_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 breads? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_terms_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Bread_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flatbread 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_valueDescriptions_Flatbread_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Bread_valueDescriptions;Flatbread;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italian 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_valueDescriptions_Italian_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Bread_valueDescriptions;Italian;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italian Herbs And Cheese 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_valueDescriptions_ItalianHerbsAndCheese_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Bread_valueDescriptions;ItalianHerbsAndCheese;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nine Grain Honey Oat 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_valueDescriptions_NineGrainHoneyOat_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Bread_valueDescriptions;NineGrainHoneyOat;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nine Grain Wheat 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_valueDescriptions_NineGrainWheat_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Bread_valueDescriptions;NineGrainWheat;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 flatbreads? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_valueTerms_Flatbread_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Bread_valueTerms;Flatbread;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 italians? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_valueTerms_Italian_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Bread_valueTerms;Italian;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 italians?;herbs?;and;cheeses?;italians? herbs?;herbs? and;and cheeses?;italians? herbs? and;herbs? and cheeses?;italian herbs and cheese 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_valueTerms_ItalianHerbsAndCheese_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Bread_valueTerms;ItalianHerbsAndCheese;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nine;grains?;honeys?;oats?;nine grains?;grains? honeys?;honeys? oats?;nine grains? honeys?;grains? honeys? oats?;nine grain honey oat 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_valueTerms_NineGrainHoneyOat_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Bread_valueTerms;NineGrainHoneyOat;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nine;grains?;wheats?;nine grains?;grains? wheats?;nine grains? wheats? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Bread_valueTerms_NineGrainWheat_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Bread_valueTerms;NineGrainWheat;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cheese 的本地化字符串。
        /// </summary>
        public static string Ingredients_Cheese_description_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Cheese_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cheeses? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Cheese_terms_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Cheese_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 American 的本地化字符串。
        /// </summary>
        public static string Ingredients_Cheese_valueDescriptions_American_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Cheese_valueDescriptions;American;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monterey Cheddar 的本地化字符串。
        /// </summary>
        public static string Ingredients_Cheese_valueDescriptions_MontereyCheddar_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Cheese_valueDescriptions;MontereyCheddar;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pepperjack 的本地化字符串。
        /// </summary>
        public static string Ingredients_Cheese_valueDescriptions_Pepperjack_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Cheese_valueDescriptions;Pepperjack;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 americans? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Cheese_valueTerms_American_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Cheese_valueTerms;American;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 montereys?;cheddars?;montereys? cheddars? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Cheese_valueTerms_MontereyCheddar_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Cheese_valueTerms;MontereyCheddar;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pepperjacks? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Cheese_valueTerms_Pepperjack_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Cheese_valueTerms;Pepperjack;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sauces 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_description_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sauces? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_terms_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chipotle Southwest 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueDescriptions_ChipotleSouthwest_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueDescriptions;ChipotleSouthwest;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Honey Mustard 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueDescriptions_HoneyMustard_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueDescriptions;HoneyMustard;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Mayonnaise 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueDescriptions_LightMayonnaise_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueDescriptions;LightMayonnaise;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mustard 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueDescriptions_Mustard_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueDescriptions;Mustard;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oil 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueDescriptions_Oil_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueDescriptions;Oil;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pepper 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueDescriptions_Pepper_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueDescriptions;Pepper;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ranch 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueDescriptions_Ranch_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueDescriptions;Ranch;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regular Mayonnaise 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueDescriptions_RegularMayonnaise_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueDescriptions;RegularMayonnaise;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sweet Onion 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueDescriptions_SweetOnion_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueDescriptions;SweetOnion;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vinegar 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueDescriptions_Vinegar_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueDescriptions;Vinegar;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chipotles?;southwests?;chipotles? southwests? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueTerms_ChipotleSouthwest_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueTerms;ChipotleSouthwest;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 honeys?;mustards?;honeys? mustards? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueTerms_HoneyMustard_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueTerms;HoneyMustard;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lights?;mayonnaises?;lights? mayonnaises? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueTerms_LightMayonnaise_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueTerms;LightMayonnaise;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mustards? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueTerms_Mustard_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueTerms;Mustard;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 oils? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueTerms_Oil_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueTerms;Oil;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 peppers? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueTerms_Pepper_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueTerms;Pepper;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ranchs? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueTerms_Ranch_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueTerms;Ranch;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 regulars?;mayonnaises?;regulars? mayonnaises? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueTerms_RegularMayonnaise_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueTerms;RegularMayonnaise;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sweets?;onions?;sweets? onions? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueTerms_SweetOnion_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueTerms;SweetOnion;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vinegars? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Sauces_valueTerms_Vinegar_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Sauces_valueTerms;Vinegar;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toppings 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_description_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 toppings? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_terms_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avocado 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_Avocado_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;Avocado;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Banana Peppers 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_BananaPeppers_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;BananaPeppers;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cucumbers 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_Cucumbers_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;Cucumbers;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_Everything_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;Everything;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Green Bell Peppers 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_GreenBellPeppers_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;GreenBellPeppers;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jalapenos 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_Jalapenos_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;Jalapenos;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lettuce 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_Lettuce_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;Lettuce;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Olives 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_Olives_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;Olives;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pickles 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_Pickles_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;Pickles;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red Onion 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_RedOnion_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;RedOnion;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spinach 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_Spinach_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;Spinach;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tomatoes 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueDescriptions_Tomatoes_VALUE {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueDescriptions;Tomatoes;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 avocados? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_Avocado_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;Avocado;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bananas?;peppers?;bananas? peppers? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_BananaPeppers_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;BananaPeppers;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cucumbers? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_Cucumbers_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;Cucumbers;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 except;but;not;no;all;everything 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_Everything_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;Everything;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 greens?;bells?;peppers?;greens? bells?;bells? peppers?;greens? bells? peppers? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_GreenBellPeppers_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;GreenBellPeppers;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 jalapenos? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_Jalapenos_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;Jalapenos;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lettuces? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_Lettuce_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;Lettuce;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 olives? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_Olives_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;Olives;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pickles? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_Pickles_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;Pickles;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 reds?;onions?;reds? onions? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_RedOnion_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;RedOnion;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 spinachs? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_Spinach_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;Spinach;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tomatoes? 的本地化字符串。
        /// </summary>
        public static string Ingredients_Toppings_valueTerms_Tomatoes_LIST {
            get {
                return ResourceManager.GetString("Ingredients.Toppings_valueTerms;Tomatoes;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length 的本地化字符串。
        /// </summary>
        public static string Length_description_VALUE {
            get {
                return ResourceManager.GetString("Length_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What size of sandwich do you want? {||} 的本地化字符串。
        /// </summary>
        public static string Length_promptDefinition_LIST {
            get {
                return ResourceManager.GetString("Length_promptDefinition;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lengths? 的本地化字符串。
        /// </summary>
        public static string Length_terms_LIST {
            get {
                return ResourceManager.GetString("Length_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Foot Long 的本地化字符串。
        /// </summary>
        public static string Length_valueDescriptions_FootLong_VALUE {
            get {
                return ResourceManager.GetString("Length_valueDescriptions;FootLong;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Six Inch 的本地化字符串。
        /// </summary>
        public static string Length_valueDescriptions_SixInch_VALUE {
            get {
                return ResourceManager.GetString("Length_valueDescriptions;SixInch;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 foots?;longs?;foots? longs? 的本地化字符串。
        /// </summary>
        public static string Length_valueTerms_FootLong_LIST {
            get {
                return ResourceManager.GetString("Length_valueTerms;FootLong;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 six;inchs?;six inchs? 的本地化字符串。
        /// </summary>
        public static string Length_valueTerms_SixInch_LIST {
            get {
                return ResourceManager.GetString("Length_valueTerms;SixInch;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to the sandwich order bot! 的本地化字符串。
        /// </summary>
        public static string message0_LIST {
            get {
                return ResourceManager.GetString("message0;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks for ordering a sandwich! 的本地化字符串。
        /// </summary>
        public static string message14_LIST {
            get {
                return ResourceManager.GetString("message14;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For sandwich toppings you have selected {Ingredients.Toppings}. 的本地化字符串。
        /// </summary>
        public static string message6_LIST {
            get {
                return ResourceManager.GetString("message6;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string NoPreference_Specials_TEMPLATE {
            get {
                return ResourceManager.GetString("NoPreference;Specials;TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I do not understand &quot;{0}&quot;.;Try again, I don&apos;t get &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        public static string NotUnderstood_Sandwich_Length_Ingredients_Bread_Ingredients_Cheese_Ingredients_Toppings_Ingredients_Sauces_Specials_DeliveryAddress_DeliveryTime_Rating_TEMPLATE {
            get {
                return ResourceManager.GetString("NotUnderstood;Sandwich;Length;Ingredients.Bread;Ingredients.Cheese;Ingredients.To" +
                        "ppings;Ingredients.Sauces;Specials;DeliveryAddress;DeliveryTime;Rating;TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 your experience today 的本地化字符串。
        /// </summary>
        public static string Rating_description_VALUE {
            get {
                return ResourceManager.GetString("Rating_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ratings? 的本地化字符串。
        /// </summary>
        public static string Rating_terms_LIST {
            get {
                return ResourceManager.GetString("Rating_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sandwich 的本地化字符串。
        /// </summary>
        public static string Sandwich_description_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What kind of {&amp;} would you like? {||} 的本地化字符串。
        /// </summary>
        public static string Sandwich_promptDefinition_LIST {
            get {
                return ResourceManager.GetString("Sandwich_promptDefinition;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sandwichs? 的本地化字符串。
        /// </summary>
        public static string Sandwich_terms_LIST {
            get {
                return ResourceManager.GetString("Sandwich_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black Forest Ham 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_BlackForestHam_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;BlackForestHam;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BLT 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_BLT_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;BLT;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buffalo Chicken 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_BuffaloChicken_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;BuffaloChicken;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chicken And Bacon Ranch Melt 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_ChickenAndBaconRanchMelt_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;ChickenAndBaconRanchMelt;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cold Cut Combo 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_ColdCutCombo_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;ColdCutCombo;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Meatball Marinara 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_MeatballMarinara_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;MeatballMarinara;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oven Roasted Chicken 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_OvenRoastedChicken_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;OvenRoastedChicken;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roast Beef 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_RoastBeef_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;RoastBeef;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotisserie Style Chicken 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_RotisserieStyleChicken_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;RotisserieStyleChicken;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spicy Italian 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_SpicyItalian_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;SpicyItalian;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steak And Cheese 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_SteakAndCheese_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;SteakAndCheese;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sweet Onion Teriyaki 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_SweetOnionTeriyaki_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;SweetOnionTeriyaki;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tuna 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_Tuna_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;Tuna;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turkey Breast 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_TurkeyBreast_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;TurkeyBreast;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Veggie 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueDescriptions_Veggie_VALUE {
            get {
                return ResourceManager.GetString("Sandwich_valueDescriptions;Veggie;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 blacks?;forests?;hams?;blacks? forests?;forests? hams?;blacks? forests? hams? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_BlackForestHam_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;BlackForestHam;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 blts? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_BLT_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;BLT;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 buffalos?;chickens?;buffalos? chickens? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_BuffaloChicken_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;BuffaloChicken;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chickens?;and;bacons?;ranchs?;melts?;chickens? and;and bacons?;bacons? ranchs?;ranchs? melts?;chickens? and bacons?;and bacons? ranchs?;bacons? ranchs? melts?;chicken and bacon ranch melt 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_ChickenAndBaconRanchMelt_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;ChickenAndBaconRanchMelt;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 colds?;cuts?;combos?;colds? cuts?;cuts? combos?;colds? cuts? combos? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_ColdCutCombo_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;ColdCutCombo;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 meatballs?;marinaras?;meatballs? marinaras? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_MeatballMarinara_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;MeatballMarinara;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ovens?;roasteds?;chickens?;ovens? roasteds?;roasteds? chickens?;ovens? roasteds? chickens? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_OvenRoastedChicken_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;OvenRoastedChicken;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 roasts?;beefs?;roasts? beefs? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_RoastBeef_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;RoastBeef;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rotis\w*s?;styles?;chickens?;rotis\w*s? styles?;styles? chickens?;rotis\w*s? styles? chickens? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_RotisserieStyleChicken_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;RotisserieStyleChicken;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 spicys?;italians?;spicys? italians? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_SpicyItalian_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;SpicyItalian;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 steaks?;and;cheeses?;steaks? and;and cheeses?;steaks? and cheeses? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_SteakAndCheese_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;SteakAndCheese;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sweets?;onions?;teriyakis?;sweets? onions?;onions? teriyakis?;sweets? onions? teriyakis? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_SweetOnionTeriyaki_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;SweetOnionTeriyaki;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tunas? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_Tuna_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;Tuna;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 turkeys?;breasts?;turkeys? breasts? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_TurkeyBreast_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;TurkeyBreast;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 veggies? 的本地化字符串。
        /// </summary>
        public static string Sandwich_valueTerms_Veggie_LIST {
            get {
                return ResourceManager.GetString("Sandwich_valueTerms;Veggie;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specials 的本地化字符串。
        /// </summary>
        public static string Specials_description_VALUE {
            get {
                return ResourceManager.GetString("Specials_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 specials? 的本地化字符串。
        /// </summary>
        public static string Specials_terms_LIST {
            get {
                return ResourceManager.GetString("Specials_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&amp;}: {:t} 的本地化字符串。
        /// </summary>
        public static string StatusFormat_DeliveryTime_TEMPLATE {
            get {
                return ResourceManager.GetString("StatusFormat;DeliveryTime;TEMPLATE", resourceCulture);
            }
        }
    }
}
